#!/usr/bin/env python3
"""Neural<->phenomenal decoupling Bayes factors (JZS Pearson).

Ports the per-participant coupling tests from the master-loop's
``atlas/pas_dynamics.py`` (``coupling`` + ``step_coupling``). Each asks whether a
neural within-trial marker tracks the *individual's* phenomenal collapse, over
and above their shared locking to the trial clock. The paper reports all three
Bayes factors below 1/3 — positive evidence *for* the null (decoupling), the
expected non-reductive signature.

The three tests (matching the manuscript, SI "Individual-level PAS
neural-correlate null" and the main-text decoupling paragraph):

  1. **coupling** (BF10 ~ 0.17, n=58) — each participant's phenomenal
     clarity-decline rate [Spearman(ClickTime, PAS)] vs their neural
     complexity-collapse rate [mean per-trial multichannel-LZc slope,
     ``mc_slope``].

  2. **step_coupling TIMING** (BF10 ~ 0.25, n=25) — each participant's neural
     spectral-entropy changepoint time vs their own PAS 4->3 logistic
     crossover time.

  3. **step_coupling MAGNITUDE** (BF10 ~ 0.28, n=58) — each participant's
     spectral-entropy early-minus-late drop vs their PAS decline
     [Spearman(ClickTime, PAS)].

For each, we take the Pearson r across participants and the JZS Pearson Bayes
factor (``pingouin.bayesfactor_pearson``).

Inputs (all regenerated by earlier reproduce.sh steps):
  * ``data/preprocessed/ClickPAS/ClickPAS.csv``          (computeClickPAS.py)
  * ``results/within_trial_complexity_pertrial.csv``     (computeWithinTrialComplexity.py; mc_slope)
  * ``results/within_trial_windows.csv``                 (computeWithinTrialComplexity.py; specent_global)

Writes ``results/decoupling_bayes_factors.csv``.

Usage
-----
    python code/analysis/computeDecouplingBF.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

_HERE = Path(__file__).resolve().parent
_CODE = _HERE.parent
for _p in (str(_CODE), str(_HERE)):
    if _p not in sys.path:
        sys.path.insert(0, _p)
import _config as C  # noqa: E402

T_TRIAL = 60.0


def _clickpas() -> pd.DataFrame:
    fp = C.DATA_PREPROC / "ClickPAS" / "ClickPAS.csv"
    if not fp.is_file():
        raise SystemExit(f"missing {fp} — run computeClickPAS.py first")
    cp = pd.read_csv(fp)
    cp = cp[~cp.DyadID.isin(C.EXCLUDE_DYADS)].copy()
    cp["subj"] = cp.DyadID.map(lambda d: f"{int(d):02d}") + "_" + cp.ParticipantID.astype(int).astype(str)
    return cp


def _clarity_decline(cp: pd.DataFrame) -> dict:
    """Per-participant Spearman(ClickTime, PAS) (negative = clarity declines)."""
    out = {}
    for s, g in cp.groupby("subj"):
        if len(g) >= 5 and g.ClickTime_s.nunique() >= 3:
            rho = stats.spearmanr(g.ClickTime_s, g.PAS).correlation
            if np.isfinite(rho):
                out[s] = rho
    return out


def _pas_crossover_per_participant(cp: pd.DataFrame) -> dict:
    """Per-participant PAS4-vs-PAS3 logistic crossover time (-b0/b1)."""
    import statsmodels.api as sm
    out = {}
    m34 = cp[cp.PAS.isin([3, 4])]
    for s, g in m34.groupby("subj"):
        if len(g) < 5 or g.PAS.nunique() < 2 or g.ClickTime_s.nunique() < 3:
            continue
        try:
            r = sm.GLM(np.asarray(g.PAS == 4, float),
                       sm.add_constant(g.ClickTime_s.values),
                       family=sm.families.Binomial()).fit()
            b0, b1 = r.params
            if b1 < 0:
                xo = -b0 / b1
                if 0 < xo < T_TRIAL:
                    out[s] = float(xo)
        except Exception:
            pass
    return out


def _changepoint(centers, y):
    """Robust 1-D changepoint: interior split minimizing within-segment SSE."""
    best, bsse = np.nan, np.inf
    for i in range(3, len(y) - 3):
        sse = ((y[:i] - y[:i].mean()) ** 2).sum() + ((y[i:] - y[i:].mean()) ** 2).sum()
        if sse < bsse:
            best, bsse = centers[i], sse
    return best


def _bf(neural: dict, behav: dict):
    """Pearson r + JZS Bayes factor across the participants in both dicts."""
    import pingouin as pg
    rows = [(neural[s], behav[s]) for s in neural
            if s in behav and np.isfinite(neural[s]) and np.isfinite(behav[s])]
    M = np.array(rows)
    r, p = stats.pearsonr(M[:, 0], M[:, 1])
    bf = float(pg.bayesfactor_pearson(r, len(M)))
    return len(M), float(r), float(p), bf


def analyze():
    cp = _clickpas()
    clar = _clarity_decline(cp)

    # --- Test 1: coupling (clarity-decline vs complexity-collapse slope) ---
    pt = pd.read_csv(C.RESULTS / "within_trial_complexity_pertrial.csv")
    comp = pt.groupby("subj").mc_slope.mean().to_dict()
    n1, r1, p1, bf1 = _bf(clar, comp)

    # --- spectral-entropy per-participant trajectory -> step-time + drop ---
    w = pd.read_csv(C.RESULTS / "within_trial_windows.csv")
    centers = np.sort(w.trial_time.unique())
    se_step, se_drop = {}, {}
    for s, g in w.groupby("subj"):
        traj = g.groupby("trial_time").specent_global.mean().reindex(centers).values
        if np.isnan(traj).any():
            continue
        se_step[s] = _changepoint(centers, traj)
        se_drop[s] = float(traj[centers < 25].mean() - traj[centers > 30].mean())

    # --- Test 2: TIMING (spectral-entropy step-time vs PAS crossover-time) ---
    pas_cross = _pas_crossover_per_participant(cp)
    n2, r2, p2, bf2 = _bf(se_step, pas_cross)

    # --- Test 3: MAGNITUDE (spectral-entropy drop vs PAS decline) ---
    pas_decl = {s: stats.spearmanr(g.ClickTime_s, g.PAS).correlation
                for s, g in cp.groupby("subj")
                if len(g) >= 5 and g.PAS.nunique() >= 2 and g.ClickTime_s.nunique() >= 3}
    n3, r3, p3, bf3 = _bf(se_drop, pas_decl)

    def verdict(bf):
        return ("evidence FOR null (decoupled)" if bf < 1 / 3
                else "inconclusive" if bf < 3 else "evidence FOR coupling")

    print("=== Neural<->phenomenal decoupling Bayes factors (JZS Pearson) ===")
    print(f"  1. coupling   (clarity-decline vs complexity-collapse) "
          f"n={n1}: r={r1:+.3f}, BF10={bf1:.2f}  [{verdict(bf1)}]  (paper 0.17)")
    print(f"  2. TIMING     (specent step-time vs PAS crossover)      "
          f"n={n2}: r={r2:+.3f}, BF10={bf2:.2f}  [{verdict(bf2)}]  (paper 0.25)")
    print(f"  3. MAGNITUDE  (specent drop vs PAS decline)             "
          f"n={n3}: r={r3:+.3f}, BF10={bf3:.2f}  [{verdict(bf3)}]  (paper 0.28)")

    out = C.RESULTS / "decoupling_bayes_factors.csv"
    C.RESULTS.mkdir(parents=True, exist_ok=True)
    pd.DataFrame([
        dict(test="coupling", description="clarity-decline (Spearman PAS~t) vs complexity-collapse (mean mc_slope)",
             n=n1, pearson_r=r1, pearson_p=p1, BF10=bf1),
        dict(test="step_coupling_timing", description="spectral-entropy changepoint time vs PAS 4->3 crossover time",
             n=n2, pearson_r=r2, pearson_p=p2, BF10=bf2),
        dict(test="step_coupling_magnitude", description="spectral-entropy early-late drop vs PAS decline (Spearman PAS~t)",
             n=n3, pearson_r=r3, pearson_p=p3, BF10=bf3),
    ]).to_csv(out, index=False)
    print(f"  saved -> {out.relative_to(C.REPO_ROOT)}")
    return dict(coupling=bf1, timing=bf2, magnitude=bf3)


if __name__ == "__main__":
    analyze()
