"""
plotFigure2_Neural.py
=========================================================================
Neural-evidence figure (manuscript Figure 4).

Three panels:

  (A) — Global scalp potential (64-channel mean) grand median, full width,
             overlaid with the free-tau S(x) = A*x*exp(-e*x) + B fit.

  (B) — Locked-τ R² scalp map (all 64 channels): where does the parameter-free
             prediction (Λ = e, τ = 3.9 s) fit, per channel? The free-τ* and
             signed-trough maps were dropped — τ is fixed everywhere else, and we
             make no per-channel magnitude prediction (baseline-confounded).

  (C) — Cohort 1/f aperiodic exponent (FOOOF) per within-trial bin,
             overlaid with the FIXED-parameter S(x) fit (Λ = e,
             τ = TAU_LOCKED = 3.9 s; only A and B estimated), the bootstrap
             95 % CI on the peak, and the 1/e + PAS 4→3 reference verticals.
             The peaked (inverted-U) shape, Λ ≈ e, and peak co-located with
             1/e and the PAS crossover are the candidate neural
             sensitivity-dynamics signature. The free-parameter results
             (Λ free, τ₀ free, nested F-test, per-participant t-test) live
             in the console output of fitExponentSensitivity.py and the
             JSON sidecar.

  The conceptual sensitivity schematic — reliability R(x) = e^{-Λx} and its
  rate sensitivity S(x) = |∂R/∂Λ| = x·e^{-Λx} — that used to be Panel A is
  now a standalone figure (manuscript Figure 2), generated by
  plotFigConcept_Sensitivity.py.

INPUTS:
  data/preprocessed/EEG/globalScalpPotential_data.mat  (Panel B GSP — canonical, µV)
  data/preprocessed/EEG/allchannel_data.mat            (Panel C scalp maps; scipy format)
  results/Figure2_perchannel_fits.csv
  results/aperiodic_exponent_within_trial.csv     (Panel D data)
  results/aperiodic_exponent_within_trial.json    (Panel D fit + CI)

OUTPUTS:
  results/Figure2_Neural.pdf  (vector)
  results/Figure2_Neural.png  (300 dpi raster for inspection)

AUTHOR: Embodied Cognitive Science Unit, OIST
DATE:   May 2026
=========================================================================
"""
import json
from pathlib import Path

import matplotlib.pyplot as plt
import mne
import numpy as np
import pandas as pd
from matplotlib.gridspec import GridSpec, GridSpecFromSubplotSpec
import scipy.io as sio

# -----------------------------------------------------------------------
# Paths
# -----------------------------------------------------------------------
HERE    = Path(__file__).resolve().parent
ROOT    = HERE.parent.parent
CSV     = ROOT / 'results' / 'Figure2_perchannel_fits.csv'
EXP_CSV = ROOT / 'results' / 'aperiodic_exponent_within_trial.csv'
EXP_JSON = ROOT / 'results' / 'aperiodic_exponent_within_trial.json'
OUT_PNG = ROOT / 'results' / 'Figure2_Neural.png'
OUT_PDF = ROOT / 'results' / 'Figure2_Neural.pdf'

# -----------------------------------------------------------------------
# Constants
# -----------------------------------------------------------------------
E            = np.e
T_TRIAL      = 60.0
TAU_LOCKED   = 3.90
TAU_BOOTUP   = 4.0   # locked boot-up commitment (s); the shared 1/e landmark is built on this
SMOOTH_WIN_S = 5.0
FS           = 10


# -----------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------

def smooth_median(mat, tTask):
    med = np.median(mat, axis=0)
    win = int(round(SMOOTH_WIN_S * FS))
    halfK = win // 2
    sm = np.convolve(med, np.ones(win) / win, mode='valid')
    t_sm = tTask[halfK: halfK + sm.size]
    return t_sm, sm


def fit_locked(t_sm, sm, tau=TAU_LOCKED):
    Teff = T_TRIAL - tau
    m = t_sm >= tau
    t_fit, y_fit = t_sm[m], sm[m]
    x = (t_fit - tau) / Teff
    s = x * np.exp(-E * x)
    X = np.column_stack([s, np.ones_like(s)])
    coef, *_ = np.linalg.lstsq(X, y_fit, rcond=None)
    A, B = float(coef[0]), float(coef[1])
    yhat = A * s + B
    ss_res = float(np.sum((y_fit - yhat) ** 2))
    ss_tot = float(np.sum((y_fit - y_fit.mean()) ** 2))
    r2 = 1 - ss_res / ss_tot
    t_trough = tau + (1.0 / E) * Teff
    return dict(A=A, B=B, R2=r2, t_trough=t_trough, yhat=yhat, t_fit=t_fit)


def make_info(ch_names):
    montage = mne.channels.make_standard_montage('standard_1020')
    info = mne.create_info(ch_names=ch_names, sfreq=1000., ch_types='eeg')
    info.set_montage(montage, match_case=False, on_missing='warn')
    return info


# -----------------------------------------------------------------------
# 1. Global scalp potential (Panel B) — from the CANONICAL precomputed GSP
# -----------------------------------------------------------------------
# IMPORTANT (regression fix, 2026-06-17): Panel B must source the canonical
# global scalp potential produced by `preprocessGSP.m`
# (data/preprocessed/EEG/globalScalpPotential_data.mat → `taskParticipantTC`,
# the per-participant baseline-corrected median time course, in µV). The
# earlier path averaged `allchannel_data.mat` (`allTC.mean(axis=1)`); that
# intermediate is regenerated by `extractAllChannels.m` from the raw EEG and
# (a) carries raw-volt units and (b) uses a different channel-mean/trial-median
# order, so it does NOT reproduce the canonical GSP fit (it rendered τ*≈2.5 s,
# A≈−0 µV, R²≈0.19 on a raw-volt axis). The canonical `taskParticipantTC`
# reproduces the published free-τ fit (τ*≈7.7 s, R²≈0.82, trough≈26.9 s) under
# the script's own smooth+fit below. `allchannel_data.mat` is still used for the
# Panel C scalp maps via the per-channel CSV (no raw-volt averaging there).
GSP_MAT = ROOT / 'data' / 'preprocessed' / 'EEG' / 'globalScalpPotential_data.mat'


def load_gsp(path):
    """Return (tTask, gsp[n_part, n_samp]) from the canonical GSP .mat.

    Handles both -v7 (scipy) and -v7.3/HDF5 (h5py) saves transparently.
    `taskParticipantTC` is the per-participant µV GSP time course.
    """
    try:                                       # -v7 (scipy-readable)
        d = sio.loadmat(str(path))
        gsp = np.asarray(d['taskParticipantTC'], dtype=float)
        tt  = np.asarray(d['tTask'], dtype=float).squeeze()
    except (NotImplementedError, ValueError):  # -v7.3 (HDF5)
        import h5py
        with h5py.File(str(path), 'r') as f:
            gsp = np.array(f['taskParticipantTC'], dtype=float)
            tt  = np.array(f['tTask'], dtype=float).squeeze()
    # Orient so that axis 0 = participants, axis 1 = time samples.
    if gsp.shape[0] == tt.size and gsp.shape[1] != tt.size:
        gsp = gsp.T
    return tt, gsp


tTask, gsp = load_gsp(GSP_MAT)
n_part = gsp.shape[0]
print(f'Global scalp potential (canonical taskParticipantTC): '
      f'n_part = {n_part}, samples = {gsp.shape[1]}, '
      f'range = [{gsp.min():.1f}, {gsp.max():.1f}] µV')

t_sm, sm_gsp = smooth_median(gsp, tTask)

# Free-tau grid search for global SP
best_r2, best_tau = -np.inf, None
for tau_try in np.arange(0.0, 20.01, 0.10):
    Teff = T_TRIAL - tau_try
    if Teff <= 0:
        continue
    m = t_sm >= tau_try
    if m.sum() < 5:
        continue
    t_f, y_f = t_sm[m], sm_gsp[m]
    x = (t_f - tau_try) / Teff
    s = x * np.exp(-E * x)
    X = np.column_stack([s, np.ones_like(s)])
    coef, *_ = np.linalg.lstsq(X, y_f, rcond=None)
    yhat = float(coef[0]) * s + float(coef[1])
    ss_res = np.sum((y_f - yhat) ** 2)
    ss_tot = np.sum((y_f - y_f.mean()) ** 2)
    r2 = 1 - ss_res / ss_tot
    if r2 > best_r2:
        best_r2, best_tau = r2, tau_try

TAU_GSP = best_tau
fit_gsp = fit_locked(t_sm, sm_gsp, tau=TAU_GSP)
print(f'Global SP (free tau = {TAU_GSP:.2f} s):  '
      f'A = {fit_gsp["A"]:+.2f}, B = {fit_gsp["B"]:+.2f}, '
      f'R² = {fit_gsp["R2"]:.3f},  trough at t = {fit_gsp["t_trough"]:.2f} s')
_fit_gsp_locked = fit_locked(t_sm, sm_gsp, tau=TAU_LOCKED)
print(f'Global SP (LOCKED tau = {TAU_LOCKED:.2f} s): '
      f'A = {_fit_gsp_locked["A"]:+.2f}, B = {_fit_gsp_locked["B"]:+.2f}, '
      f'R² = {_fit_gsp_locked["R2"]:.3f},  trough at t = {_fit_gsp_locked["t_trough"]:.2f} s')

# -----------------------------------------------------------------------
# 2. Scalp-map data — all 64 channels, no filtering
# -----------------------------------------------------------------------
df = pd.read_csv(str(CSV))
N_TOTAL = len(df)

ch_all      = df['channel'].tolist()
R2_free_all = df['R2_free'].to_numpy()
tau_all     = df['tau_star'].to_numpy()
A_lock_all  = df['A_lock'].to_numpy()
R2_lock_all = df['R2_lock'].to_numpy()
info_all    = make_info(ch_all)

trough_shape  = (1.0 / E) * np.exp(-1.0)
trough_raw    = A_lock_all * trough_shape + df['B_lock'].to_numpy()

print(f'\nScalp-map data: all {N_TOTAL} channels')
print(f'  tau* range:   [{tau_all.min():.2f}, {tau_all.max():.2f}] s')
print(f'  R2_free range: [{R2_free_all.min():.3f}, {R2_free_all.max():.3f}]')
print(f'  R2_lock range: [{R2_lock_all.min():.3f}, {R2_lock_all.max():.3f}]')
print(f'  trough range:  [{trough_raw.min():.3f}, {trough_raw.max():.3f}] µV')

# -----------------------------------------------------------------------
# 3. Aperiodic-exponent data + fit (Panel D)
# -----------------------------------------------------------------------
exp_df = pd.read_csv(str(EXP_CSV))
exp_t   = exp_df['trial_time'].to_numpy()
exp_mu  = exp_df['exponent_mean'].to_numpy()
exp_sem = exp_df['exponent_sem'].to_numpy()

with open(EXP_JSON) as fh:
    exp_meta = json.load(fh)
# Panel D leads with the FIXED-parameter form (Λ = e, τ = TAU_LOCKED = 3.9 s) —
# the headline reads as a parameter-free prediction test that matches the
# framework's idiom on Panels B/C. The free-parameter results stay in the
# console (fitExponentSensitivity.py prints them).
exp_R2_fixed = exp_meta['head_to_head_R2']['sensitivity_peak_lambda_e']
exp_ci   = exp_meta['bootstrap_peak_ci']          # {n_resamples, median_s, ci95_s}
# PAS 4->3 crossover: use the canonical within-participant value (28.4 s, same
# as Fig 5 and the main text) from Figure3_crossover_stats.csv — not the per-bin
# sidecar value (exp_meta['framework']['pas_crossover_s'] = 29.0).
pas_s    = float(pd.read_csv(ROOT / 'results' / 'Figure3_crossover_stats.csv')['trial_crossover_s'].iloc[0])
t_oe_exp = TAU_BOOTUP + (T_TRIAL - TAU_BOOTUP) / E  # 1/e landmark of the shared structure (4 s boot-up + 1/e decay) — same anchor as Fig 5, not tied to the fit's τ

print(f'\nAperiodic exponent (Panel D): n={exp_meta["n_participants"]}, '
      f'FIXED-form S(x) [Λ = e, τ = {TAU_LOCKED:.1f} s]: R²={exp_R2_fixed:.3f}, '
      f'peak at t = {t_oe_exp:.1f} s = 1/e (by construction); '
      f'bootstrap 95 % CI on peak = [{exp_ci["ci95_s"][0]:.0f}, '
      f'{exp_ci["ci95_s"][1]:.0f}] s')

# -----------------------------------------------------------------------
# 4. Figure  — 2 × 2 layout:  A | B   /   C(triptych) | D
# -----------------------------------------------------------------------
plt.rcParams.update({
    'font.size': 10,
    'axes.spines.top': False,
    'axes.spines.right': False,
})

fig = plt.figure(figsize=(12.0, 8.5))
gs_outer = GridSpec(
    2, 2,
    height_ratios=[0.85, 1.1],
    width_ratios=[0.85, 1.15],
    hspace=0.34, wspace=0.30,
    left=0.06, right=0.96, top=0.95, bottom=0.07,
)
# Top row (A): the global scalp potential, spanning the full width.
# Bottom-left (B): a single locked-τ R² scalp map; bottom-right (C): the
# aperiodic exponent. The conceptual sensitivity schematic that used to be
# Panel A is now a standalone figure in the main text, not a panel here.
gs_bot_left  = GridSpecFromSubplotSpec(1, 1, subplot_spec=gs_outer[1, 0])
gs_bot_right = GridSpecFromSubplotSpec(1, 1, subplot_spec=gs_outer[1, 1])

# ---- TOP (A): Global scalp potential + S(x) fit (spans the full width) ----
ax_b = fig.add_subplot(gs_outer[0, :])
col_gsp = '#c44e52'

ax_b.plot(t_sm, sm_gsp, color=col_gsp, lw=1.0, alpha=0.35,
          label='Global scalp potential (64-ch mean)')
ax_b.plot(fit_gsp['t_fit'], fit_gsp['yhat'], color=col_gsp, lw=2.5,
          label=rf'$\tau^*$={TAU_GSP:.0f} s,  '
                rf'A={fit_gsp["A"]:+.0f} $\mu$V,  '
                rf'$R^2$={fit_gsp["R2"]:.2f}')

y_trough_raw = fit_gsp['A'] * (1.0 / E) * np.exp(-1.0) + fit_gsp['B']
ax_b.plot(fit_gsp['t_trough'], y_trough_raw, 'o',
          mfc=col_gsp, mec='white', mew=1.2, ms=8, zorder=5)
ax_b.annotate(rf't = {fit_gsp["t_trough"]:.0f} s',
              xy=(fit_gsp['t_trough'], y_trough_raw),
              xytext=(0, 10), textcoords='offset points',
              ha='center', va='bottom', fontsize=9, fontweight='bold',
              color=col_gsp)

ax_b.axvline(TAU_GSP, color='0.5', ls=':', lw=1.0)
ax_b.axhline(0, color='k', lw=0.4, alpha=0.3)

ax_b.set_xlim(t_sm.min(), t_sm.max())
ax_b.set_xlabel('Time (s)')
ax_b.set_ylabel(r'Scalp potential ($\mu$V)')
ax_b.set_title(rf'Global scalp potential — $S(x)$ fit  '
               rf'(free $\tau^*$ = {TAU_GSP:.0f} s)',
               pad=6, fontsize=10)
ax_b.legend(loc='upper right', frameon=False, fontsize=7.5)

# ---- BOTTOM LEFT (B): locked-τ R² scalp map ----
# A single map of where the parameter-free prediction (locked τ = 3.9 s) fits,
# per channel. We drop the free-τ* and signed-trough maps: τ is fixed everywhere
# else, and we make no per-channel magnitude prediction (the absolute trough
# amplitude is baseline-confounded under the minimal GSP preprocessing).
ax_topo = fig.add_subplot(gs_bot_left[0, 0])
im_r2, _ = mne.viz.plot_topomap(
    R2_lock_all, info_all, axes=ax_topo, show=False, cmap='viridis',
    vlim=(0, 1), contours=6, sensors=True, extrapolate='local',
)
ax_topo.set_title(r'$R^2$ of the locked-$\tau$ $S(x)$ fit per channel'
                  '\n' r'($\Lambda = e$, $\tau = 4$ s)', pad=6, fontsize=9)
cb = fig.colorbar(im_r2, ax=ax_topo, shrink=0.78, pad=0.05); cb.set_label(r'$R^2$')

# ---- BOTTOM RIGHT (D): 1/f aperiodic exponent tracks S(x) ----
ax_d = fig.add_subplot(gs_bot_right[0, 0])
col_exp = '#1f4e79'
col_fit = '#000000'
col_oe  = '#d62728'
col_pas = '#2ca02c'

# Peak 95 % CI band (bootstrap result from fitExponentSensitivity.py).
ci_lo, ci_hi = exp_ci['ci95_s']
ax_d.axvspan(ci_lo, ci_hi, color='0.85', alpha=0.7, zorder=0,
             label=f'Peak 95% CI [{ci_lo:.0f}, {ci_hi:.0f}] s')

# Data: cohort mean ± SEM.
ax_d.errorbar(exp_t, exp_mu, yerr=exp_sem, color=col_exp,
              lw=1.4, marker='o', ms=4, capsize=2, elinewidth=0.8,
              label='1/f exponent (mean ± SEM)', zorder=2)

# S(x) fit overlay — FIXED-parameter form (Λ = e, τ = TAU_LOCKED = 3.9 s).
# Only A and B are estimated, by 1-D least squares; the shape is parameter-free.
Teff_d = T_TRIAL - TAU_LOCKED
mask_d = exp_t >= TAU_LOCKED
xd = (exp_t[mask_d] - TAU_LOCKED) / Teff_d
sd = np.where(xd > 0, xd * np.exp(-E * xd), 0.0)
Xd_mat = np.column_stack([sd, np.ones_like(sd)])
A_d, B_d = np.linalg.lstsq(Xd_mat, exp_mu[mask_d], rcond=None)[0]
t_fit_d = np.linspace(TAU_LOCKED, T_TRIAL, 300)
x_fit_d = (t_fit_d - TAU_LOCKED) / Teff_d
y_fit_d = A_d * x_fit_d * np.exp(-E * x_fit_d) + B_d
ax_d.plot(t_fit_d, y_fit_d, color=col_fit, lw=2.2, zorder=3,
          label=(rf'$S(x)$ fit: $\Lambda = e$, $\tau = {TAU_LOCKED:.0f}$ s (fixed), '
                 rf'$R^2 = {exp_R2_fixed:.2f}$'))

# Verticals: 1/e (locked-τ convention) and PAS 4→3.
ax_d.axvline(t_oe_exp, color=col_oe, ls=':', lw=1.5, zorder=1,
             label=f'1/e ({t_oe_exp:.0f} s)')
ax_d.axvline(pas_s, color=col_pas, ls='-.', lw=1.5, zorder=1,
             label=f'PAS 4→3 ({pas_s:.0f} s)')

ax_d.set_xlim(0, 60)
ax_d.set_xlabel('Time (s)')
ax_d.set_ylabel('Aperiodic exponent')
ax_d.set_title(r'1/f aperiodic exponent tracks $S(x)$' '\n'
               rf'(bootstrap peak CI brackets 1/e and PAS 4→3)',
               pad=6, fontsize=10)
# Boxed legend with an opaque white background: the lower-centre legend sits
# over the CI band and reference verticals, so an opaque box keeps it legible.
ax_d.legend(loc='lower center', fontsize=11.25, frameon=True,
            facecolor='white', edgecolor='0.7', framealpha=1.0).set_zorder(5)

# ---- Panel letters ----
# No baked-in super-title: the figure number and title are supplied by the
# LaTeX \caption (journal auto-numbering), avoiding "Figure 2 ... Figure 2 —"
# duplication. (N is reported in the caption and Panel D legend.)

for ax, letter in [(ax_b, 'A'), (ax_topo, 'B'), (ax_d, 'C')]:
    ax.text(-0.08, 1.08, letter, transform=ax.transAxes,
            fontsize=16, fontweight='bold', va='bottom', ha='left')

# ---- Save ----
fig.savefig(str(OUT_PNG), dpi=300, bbox_inches='tight', facecolor='w')
fig.savefig(str(OUT_PDF), bbox_inches='tight', facecolor='w')
print(f'Saved: {OUT_PNG}')
print(f'Saved: {OUT_PDF}')
plt.close(fig)
