%% plotFigure3_Perceptual.m
% =========================================================================
% PNAS Figure 3: Perceptual Evidence — Sensitivity Dynamics and PAS
% =========================================================================
%
% Two-panel figure linking sensitivity dynamics to perceptual awareness:
%
%   Panel A — Sensitivity of R(x) to Rate Perturbations (Schematic)
%     The reliability function R(x) = exp(-lambda*x) and its sensitivity
%     dR/dlambda (normalized), which reaches its trough at x = 1/lambda.
%     At lambda = e, this trough occurs at x = 1/e — the optimal stopping
%     point. The left half is the "rejection phase" (low sensitivity,
%     system robust); the right half is the "selection phase" (high
%     sensitivity, system fragile).
%
%     Equivalent multiplicative-rate form (setting tau = 0 for clarity):
%     writing k = lambda / T, the decay becomes R(t) = exp(-k*t), a rate
%     with units of inverse time. The horizon T then enters the dynamics
%     through a single multiplicative scaling of k, rather than through
%     explicit normalization of the coordinate — so no clock or explicit
%     representation of the horizon is required for the system to realize
%     the 1/e trough.
%
%   Panel B — PAS Ratings Over Trial Time (unsmoothed)
%     Per-participant PAS proportions in DISJOINT 1-s bins, averaged
%     across participants (no moving-window smoothing, no overlapping
%     bins).  Shows the four PAS levels as stepped traces.  No fitted
%     rate-sensitivity curve is overlaid on this panel.
%
% INPUT:
%   ../../data/preprocessed/EEG/globalScalpPotential_stats.mat
%   ../../results/pas_unsmoothed_proportions.csv
%     (generated by code/analysis/_scratch/pas_unsmoothed.py)
%
% OUTPUT:
%   ../../results/Figure3_Perceptual.png  (600 dpi)
%
% AUTHOR: Embodied Cognitive Science Unit, OIST
% DATE:   April 2026
% =========================================================================

clear; clc; close all;

%% ========================================================================
%  1. LOAD PRECOMPUTED RESULTS
%  ========================================================================

statsFile  = '../../data/preprocessed/EEG/globalScalpPotential_stats.mat';
unsmFile   = '../../results/pas_unsmoothed_proportions.csv';

for f = {statsFile, unsmFile}
    if ~isfile(f{1})
        error('Missing: %s\nSee README for instructions.', f{1});
    end
end

S      = load(statsFile);
UNSM   = readtable(unsmFile);

tau    = S.grandTau;
T      = 60;
lambda = exp(1);
tPeak  = tau + (T - tau) / lambda;

fprintf('Loaded precomputed results:\n');
fprintf('  GSP: N=%d, grand R^2=%.3f\n', S.nPart, S.grandR2);
fprintf('  Unsmoothed PAS: %d rows (4 levels x bin centers)\n', height(UNSM));

%% ========================================================================
%  2. STYLING
%  ========================================================================

col_decay = [0.50 0.50 0.50];    % Grey for R(x)
col_sens  = [0.85 0.20 0.10];    % Red for sensitivity curve
col_early = [0.15 0.45 0.75];    % Blue
col_late  = [0.85 0.55 0.10];    % Orange

col_pas = [0.65 0.65 0.65;       % PAS 1 grey
           0.93 0.69 0.13;       % PAS 2 amber
           0.85 0.33 0.10;       % PAS 3 orange
           0.00 0.00 0.00];      % PAS 4 black
lw_pas  = [1.5 1.5 2.0 2.5];

font_main  = 11;
font_label = 12;
font_title = 13;

%% ========================================================================
%  3. RESHAPE UNSMOOTHED PAS PROPORTIONS FOR PLOTTING
%  ========================================================================
%  UNSM is long-form (bin_center, pas_level, grand_prop, grand_sem,
%  n_participants).  Reshape into (4 x nBin) for plotting convenience.

binCenters = unique(UNSM.bin_center, 'stable')';    % 1 x nBin
nBin       = length(binCenters);
tauLock    = 3.90;                                  % kept for reference xline

grandProp_unsm = nan(4, nBin);
grandSEM_unsm  = nan(4, nBin);
for lv = 1:4
    m = UNSM.pas_level == lv;
    [~, idx] = ismember(UNSM.bin_center(m), binCenters);
    grandProp_unsm(lv, idx) = UNSM.grand_prop(m) * 100;  % to percent
    grandSEM_unsm(lv, idx)  = UNSM.grand_sem(m)  * 100;
end

%% ========================================================================
%  4. CREATE FIGURE — 2 rows
%  ========================================================================

fprintf('Creating Figure 3 ...\n');

fig = figure('Units', 'inches', 'Position', [0.5 0.5 7.5 6], 'Color', 'w', ...
    'PaperUnits', 'inches', 'PaperSize', [7.5 6], 'PaperPosition', [0 0 7.5 6]);

%% ---- Panel A: Reliability R(x) and its sensitivity ---------------------

ax_a = subplot(2,1,1);
hold on;

x = linspace(0, 1.0, 300);
Rx         = exp(-lambda * x);             % Reliability function
dRdlam     = -x .* exp(-lambda * x);       % dR/dlambda (negative)
dRdlam_norm = dRdlam / abs(min(dRdlam));   % Normalize so trough = -1
xTrough_norm = 1/lambda;

% Shade early/late FIRST so curves draw on top
yyaxis right;
ylim([-1.25 0.05]);
yl = ylim;
fill([0 xTrough_norm xTrough_norm 0], [yl(1) yl(1) yl(2) yl(2)], ...
    col_early, 'FaceAlpha', 0.06, 'EdgeColor', 'none', ...
    'HandleVisibility', 'off');
fill([xTrough_norm x(end) x(end) xTrough_norm], [yl(1) yl(1) yl(2) yl(2)], ...
    col_late, 'FaceAlpha', 0.06, 'EdgeColor', 'none', ...
    'HandleVisibility', 'off');

text(0.08, 0.85, 'Rejection phase', ...
    'FontSize', 9, 'Color', col_early, 'FontAngle', 'italic', ...
    'Units', 'normalized');
text(0.58, 0.85, 'Selection phase', ...
    'FontSize', 9, 'Color', col_late, 'FontAngle', 'italic', ...
    'Units', 'normalized');

% Plot curves on top of shading
yyaxis left;
plot(x, Rx, '-', 'Color', col_decay, 'LineWidth', 2.5);
ylabel('R(x) = e^{-\lambda x}', 'FontSize', font_label, 'Color', col_decay);
set(gca, 'YColor', col_decay);
ylim([-0.05 1.05]);

yyaxis right;
plot(x, dRdlam_norm, '-', 'Color', col_sens, 'LineWidth', 3);
ylabel({'\partial R / \partial\lambda', '(normalized)'}, ...
    'FontSize', font_label, 'Color', col_sens);
set(gca, 'YColor', col_sens);
ylim([-1.25 0.05]);
set(gca, 'Color', 'none');
ax_a.Layer = 'top';

% Trough marker
plot(xTrough_norm, -1.0, '^', 'MarkerSize', 10, 'MarkerFaceColor', col_sens, ...
    'MarkerEdgeColor', 'k', 'LineWidth', 0.5);
text(xTrough_norm + 0.03, -1.08, 'x = 1/\lambda = 1/e', ...
    'FontSize', 10, 'FontWeight', 'bold', 'Color', col_sens);

% Re-draw sensitivity curve on top
plot(x, dRdlam_norm, '-', 'Color', col_sens, 'LineWidth', 2.5, ...
    'HandleVisibility', 'off');

hold off;
xlabel({'Dimensionless time  x = t / T', ...
        'equivalently  \lambda x = k t,   k = \lambda / T'}, ...
        'FontSize', font_label, 'Interpreter', 'tex');
title('(A)  Sensitivity of reliability R(x) to rate perturbations', ...
    'FontSize', font_title, 'FontWeight', 'bold');
set(gca, 'TickDir', 'out', 'FontSize', font_main, 'Box', 'off');
xlim([0 1.0]);

lg = legend('R(x): reliability of metastable state', ...
            '\partialR/\partial\lambda: rate sensitivity', ...
            'Location', 'southeast');
lg.FontSize = 9; lg.Box = 'on';
lg.Color = 'w';
lg.EdgeColor = [0.7 0.7 0.7];

%% ---- Panel B: Unsmoothed (disjoint 1-s bin) PAS rating time course ------

ax_b = subplot(2,1,2);
hold on;

% PAS levels (4 curves + SEM shading) from disjoint-bin unsmoothed data.
% Plotted as step-function traces centred on bin centres to honour the
% fact that each bin is independent (no moving average across neighbours).
pasHandles = gobjects(4,1);
for lv = 1:4
    validW = ~isnan(grandProp_unsm(lv,:));
    xw = binCenters(validW);
    yw = grandProp_unsm(lv, validW);
    ew = grandSEM_unsm(lv, validW);
    ew(isnan(ew)) = 0;
    fill([xw, fliplr(xw)], [yw+ew, fliplr(yw-ew)], ...
        col_pas(lv,:), 'FaceAlpha', 0.10, 'EdgeColor', 'none', ...
        'HandleVisibility', 'off');
    pasHandles(lv) = stairs(xw - 0.5, yw, '-', ...
        'Color', col_pas(lv,:), 'LineWidth', lw_pas(lv), ...
        'DisplayName', sprintf('PAS %d', lv));
end

% tau lock marker (subtle)
xline(tauLock, ':', 'Color', [0.5 0.5 0.5], 'LineWidth', 1.0, ...
    'Alpha', 0.6, 'HandleVisibility', 'off');

hold off;
xlim([0 T]); ylim([0 85]);
xlabel('Trial time (s)', 'FontSize', font_label);
ylabel('Proportion of clicks (%)', 'FontSize', font_label);
title('(B)  PAS ratings over trial time (unsmoothed, disjoint 1-s bins)', ...
    'FontSize', font_title, 'FontWeight', 'bold');

% Legend: PAS 4 at top (highest clarity first), then 3, 2, 1.
lgd = legend(flipud(pasHandles), 'Location', 'southeast', 'Box', 'on', ...
    'FontSize', 9, 'NumColumns', 2);
set(lgd, 'Color', 'w', 'EdgeColor', [0.7 0.7 0.7]);
set(gca, 'TickDir', 'out', 'FontSize', font_main, 'Box', 'off');

%% ========================================================================
%  5. SAVE
%  ========================================================================

outFile = '../../results/Figure3_Perceptual.png';
exportgraphics(fig, outFile, 'Resolution', 600);
fprintf('  Saved: %s (600 dpi)\n', outFile);

%% ========================================================================
%  6. SUMMARY
%  ========================================================================

fprintf('\n==========================================================\n');
fprintf('  FIGURE 3 SUMMARY (Perceptual Evidence)\n');
fprintf('==========================================================\n');
fprintf('  Panel A — Sensitivity Schematic\n');
fprintf('    R(x) = exp(-lambda*x), trough at x = 1/e\n');
fprintf('    lambda = e (fixed, not fitted)\n');
fprintf('  --\n');
fprintf('  Panel B — Unsmoothed PAS time course\n');
fprintf('    Bin width: %.1f s (disjoint, no moving window)\n', 1.0);
fprintf('    n bins: %d,  n participants: %d\n', nBin, S.nPart);
fprintf('==========================================================\n');
fprintf('Done.\n');
